name: 'Auto Author Assign'
on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  pull-requests: write

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/auto-author-assign@7e15cd70c245ad136377c3fab3479815df10d844 # (latest, untagged)
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
