name: "Pull Request Labeler"
on:
  pull_request_target:
jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@b2b2c20d4426b3c8035c21473ead775a153cf866 # (latest, untagged)
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
